In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
titanic = sns.load_dataset('titanic')

In [3]:
titanic

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [7]:
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [9]:
titanic.dtypes

survived          int64
pclass            int64
sex              object
age             float64
sibsp             int64
parch             int64
fare            float64
embarked         object
class          category
who              object
adult_male         bool
deck           category
embark_town      object
alive            object
alone              bool
dtype: object

In [11]:
titanic.describe() 
# dtypes 를 통해 확인하면, 각 열의 데이터타입이 int나 float인 경우만 출력하는걸 알 수 있다.
# count 는 각각의 열에 존재하는 데이터의 총 갯수를 말함.
# std는 각 열의 표준편차
# min은 각 열의 최소값
#25% 50% 75% 는 각 열의 25% 50% 75% 값
#max 는 각 열의 최대값

survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [13]:
titanic.isnull().sum()  # age는 NaN값이 177개 , embarked 는 2개, deck 는 688개 , embark_town은 2개다.

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [15]:
titanic['age'] = titanic['age'].fillna(titanic['age'].median()) # 나이를 중앙값으로 치환

In [17]:
titanic['embarked'] = titanic['embarked'].fillna(titanic['embarked'].mode().iloc[0]) # embarked 는 최빈값으로 빈칸대체

In [19]:
print(titanic['age'].isnull().sum())
print(titanic['embarked'].isnull().sum()) 
# 비어있는 값을 대체후 빈칸 확인결과 0개!

0
0


In [21]:
titanic['sex'] = titanic['sex'].map({'male': 0, 'female': 1})
titanic['alive'] = titanic['alive'].map({'yes': 1, 'no': 0})
titanic['embarked'] = titanic['embarked'].map({'C': 0, 'Q': 1, 'S': 2,})

In [23]:
titanic

survived  pclass  sex   age  sibsp  parch     fare  embarked   class  \
0           0       3    0  22.0      1      0   7.2500         2   Third   
1           1       1    1  38.0      1      0  71.2833         0   First   
2           1       3    1  26.0      0      0   7.9250         2   Third   
3           1       1    1  35.0      1      0  53.1000         2   First   
4           0       3    0  35.0      0      0   8.0500         2   Third   
..        ...     ...  ...   ...    ...    ...      ...       ...     ...   
886         0       2    0  27.0      0      0  13.0000         2  Second   
887         1       1    1  19.0      0      0  30.0000         2   First   
888         0       3    1  28.0      1      2  23.4500         2   Third   
889         1       1    0  26.0      0      0  30.0000         0   First   
890         0       3    0  32.0      0      0   7.7500         1   Third   

       who  adult_male deck  embark_town  alive  alone  
0      man        True  NaN  Southampton      0  False  
1    woman       False    C    Cherbourg      1  False  
2    woman       False  NaN  Southampton      1   True  
3    woman       False    C  Southampton      1  False  
4      man        True  NaN  Southampton      0   True  
..     ...         ...  ...          ...    ...    ...  
886    man        True  NaN  Southampton      0   True  
887  woman       False    B  Southampton      1   True  
888  woman       False  NaN  Southampton      0  False  
889    man        True    C    Cherbourg      1   True  
890    man        True  NaN   Queenstown      0   True  

[891 rows x 15 columns]

In [25]:
print(titanic['sex'].head(),titanic['alive'].head() , titanic['embarked'].head())

0    0
1    1
2    1
3    1
4    0
Name: sex, dtype: int64 0    0
1    1
2    1
3    1
4    0
Name: alive, dtype: int64 0    2
1    0
2    2
3    2
4    2
Name: embarked, dtype: int64


In [27]:
titanic['family_size'] = titanic['sibsp'] + titanic['parch'] + 1
#SibSp : 타이타닉 호에 동승한 자매 / 배우자의 수
#Parch : 타이타닉 호에 동승한 부모 / 자식의 수
#따라서 family_size 는 나 + 배우자 + 형제자매 + 부모 + 자식 의 수를 합친 총 인원수!
print(titanic['family_size'].head())

0    2
1    2
2    1
3    2
4    1
Name: family_size, dtype: int64


In [29]:
titanic = titanic[['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked', 'family_size']]
X = titanic.drop('survived', axis=1)
y = titanic['survived']

In [31]:
#로지스틱 회귀 머신러닝 시작!
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler

In [33]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [35]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [37]:
from sklearn.linear_model import LogisticRegression #로지스틱 회귀 모델 생성
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [39]:
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [41]:
y_pred = model.predict(X_test)
print(f"Accuracy: {accuracy_score(y_test, y_pred)}")
print(f"Classification Report:\n{classification_report(y_test, y_pred)}")
print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}")

Accuracy: 0.8044692737430168
Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.86      0.84       105
           1       0.78      0.73      0.76        74

    accuracy                           0.80       179
   macro avg       0.80      0.79      0.80       179
weighted avg       0.80      0.80      0.80       179

Confusion Matrix:
[[90 15]
 [20 54]]


In [43]:
#랜덤포레스트 머신러닝 시작!
from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

In [45]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

In [47]:
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [49]:
y_pred_rf = rf_model.predict(X_test)
mse_rf = mean_squared_error(y_test, y_pred_rf)
print(mse_rf)

0.13605153814540247


In [51]:
#XGBoost 머신러닝 시작!
import xgboost as xgb

In [53]:
xgb_model = xgb.XGBRegressor(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)
xgb_model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.1, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=3, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=100, n_jobs=None,
             num_parallel_tree=None, random_state=42, ...)

In [55]:
y_pred_xgb = xgb_model.predict(X_test)
mse_xgb = mean_squared_error(y_test, y_pred_xgb)
mse_xgb

0.12981004899201257

In [57]:
#의사결정나무 시작!
from sklearn.tree import DecisionTreeClassifier

In [59]:
model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)


y_pred_tree = model.predict(X_test)

print(f"Accuracy_tree: {accuracy_score(y_test, y_pred_tree)}")
print(f"Classification Report_tree:\n{classification_report(y_test, y_pred_tree)}")
print(f"Confusion Matrix_tree:\n{confusion_matrix(y_test, y_pred_tree)}")

Accuracy_tree: 0.770949720670391
Classification Report_tree:
              precision    recall  f1-score   support

           0       0.83      0.76      0.80       105
           1       0.70      0.78      0.74        74

    accuracy                           0.77       179
   macro avg       0.77      0.77      0.77       179
weighted avg       0.78      0.77      0.77       179

Confusion Matrix_tree:
[[80 25]
 [16 58]]


In [61]:
tree = {}
best_score = 0
for x in range(0,100):
    best_score = x+1
    
    model = DecisionTreeClassifier(random_state=best_score)  # for 구문을 이용해 random_state 값을 1부터 100까지 시험!
    model.fit(X_train, y_train)
    y_pred_tree6 = model.predict(X_test)
    Accuracy_tree6 = accuracy_score(y_test, y_pred_tree6)
    
    tree[best_score] = (Accuracy_tree6)  # random_state를  키값으로 지정하여, 키값에 해당하는 accuracy값을 딕셔너리 형태로 저장!
    

print(max(tree.values())) # random_state를 1부터 100까지 넣었을때 나온 값중, 가장 큰 accuracy 값을 출력!
score = [k for k, v in tree.items() if v == max(tree.values()) ] #가장 큰 accuracy 값에 해당하는 키값을 저장!

0.7932960893854749


In [63]:
score # 최대 accuracy 값에 해당하는 random_state 값이 2개다!

[31, 76]

In [65]:
#score 리스트의 요소값을 random_state에 할당하여 모델 재학습!
model = DecisionTreeClassifier(random_state=score[0]) # score 리스트는 최대 accuracy 값에 해당하는 키값 컬렉션이므로, 아무거나 넣어도됨!
model.fit(X_train, y_train)
y_pred_tree2 = model.predict(X_test)

print(f"Accuracy_tree: {accuracy_score(y_test, y_pred_tree2)}")
print(f"Classification Report_tree:\n{classification_report(y_test, y_pred_tree2)}")
print(f"Confusion Matrix_tree:\n{confusion_matrix(y_test, y_pred_tree2)}")

Accuracy_tree: 0.7932960893854749
Classification Report_tree:
              precision    recall  f1-score   support

           0       0.84      0.80      0.82       105
           1       0.73      0.78      0.76        74

    accuracy                           0.79       179
   macro avg       0.79      0.79      0.79       179
weighted avg       0.80      0.79      0.79       179

Confusion Matrix_tree:
[[84 21]
 [16 58]]


In [67]:
# 최종모델 : 첫번째 모델로 random_state최적값을 찾은 다음, 최적값을 2번째 모델 random_state 값에 입력하여 모델 재학습!
tree2 = {}
best_score2 = 0
for x in range(0,100):
    best_score2 = x+1
    
    model = DecisionTreeClassifier(random_state=best_score2)  # for 구문을 이용해 random_state 값을 1부터 100까지 넣어서 모델 시험!
    model.fit(X_train, y_train)
    y_pred_tree3 = model.predict(X_test)
    Accuracy_tree2 = accuracy_score(y_test, y_pred_tree3)
    
    tree2[best_score2] = (Accuracy_tree2)  # random_state를  키값으로 지정하여, 키값에 해당하는 accuracy값을 딕셔너리 형태로 저장!
    
score2 = [k for k, v in tree.items() if v == max(tree2.values()) ] #가장 큰 accuracy 값에 해당하는 키값을 저장!

model = DecisionTreeClassifier(random_state=score2[0]) # score 리스트는 최대 accuracy 값에 해당하는 키값 컬렉션이므로, 아무거나 넣어도됨!
model.fit(X_train, y_train)
y_pred_tree4 = model.predict(X_test)

print(f"Accuracy_tree: {accuracy_score(y_test, y_pred_tree4)}")
print(f"Classification Report_tree:\n{classification_report(y_test, y_pred_tree4)}")
print(f"Confusion Matrix_tree:\n{confusion_matrix(y_test, y_pred_tree4)}")


Accuracy_tree: 0.7932960893854749
Classification Report_tree:
              precision    recall  f1-score   support

           0       0.84      0.80      0.82       105
           1       0.73      0.78      0.76        74

    accuracy                           0.79       179
   macro avg       0.79      0.79      0.79       179
weighted avg       0.80      0.79      0.79       179

Confusion Matrix_tree:
[[84 21]
 [16 58]]
